#!/usr/bin/env python

import sys

from rqt_marker_recorder.my_module import MRPlugin
from rqt_gui.main import Main

plugin = 'rqt_marker_recorder'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
